POST http://localhost:3001/api/users
Content-Type: application/json

{
    "id": 11,
    "username": "Mary",
    "password": "SuqK",
    "email": "y.qgqlwk@djpxl.ar",
    "display_name": "文艳",
    "groups": null
}